
# reuse-lang - a pure functional lisp-like language for writing
# reusable algorithms in an extremely portable way.
#
# Written in 2015 by Jesper Oskarsson jesosk@gmail.com
#
# To the extent possible under law, the author(s) have dedicated all copyright
# and related and neighboring rights to this software to the public domain worldwide.
# This software is distributed without any warranty.
#
# You should have received a copy of the CC0 Public Domain Dedication along with this software.
# If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

language: cpp
env:
    - NODE_VERSION="0.10"
    - NODE_VERSION="0.11"
    - NODE_VERSION="0.12"
    - NODE_VERSION="iojs"
    - NODE_VERSION="4.0"
    - NODE_VERSION="4.1"
    - NODE_VERSION="4.2"
    - NODE_VERSION="5.1"
os:
    - linux
    - osx

before_install:
  - rm -rf ~/.nvm
  - git clone https://github.com/creationix/nvm.git ~/.nvm
  - source ~/.nvm/nvm.sh
  - nvm install $NODE_VERSION
  - node --version

install: npm install

#script: npm test

script: npm run-script check-dependencies && npm test && npm run-script coverage-travis-ci
after_script: npm run-script coverage-coveralls-io
