#!/usr/bin/env bash

set -e

[ -d reuse_modules ] || mkdir reuse_modules

if [[ "$2" == git@* ]]; then
    repo_path="reuse_modules/.tmp.gitrepo.$1-$3"
    [ -d $repo_path ] || git clone -q "$2" --depth 1 --branch "$3" --single-branch "$repo_path"
    cp "$repo_path/$4" reuse_modules/.tmp
else
    if [ "$(uname)" = "Darwin" ]; then
        curl -o reuse_modules/.tmp -sL "$2"
    else
        curl -o reuse_modules/.tmp -sL "$2"
    fi
fi
if [ "$(uname)" = "Darwin" ]; then
    hash=$(shasum -a 256 reuse_modules/.tmp | awk '{print $1}')
else
    hash=$(sha256sum reuse_modules/.tmp | awk '{print $1}')
fi

echo "$1 $hash"

mv reuse_modules/.tmp reuse_modules/$1-$hash.reuse
