#!/usr/bin/env bash

set -e

if [ "$(uname)" = "Darwin" ] ; then
    root_path=$(dirname $(ruby -e "print File.realpath(\"$0\")"))
else
    root_path=$(dirname $(readlink -f "$0"))
fi

$root_path/bin/reusec $@
