var i_51_50_95add = function (a, b) { return (a + b) | 0; };
var i_51_50_95subtract = function (a, b) { return (a - b) | 0; };
var i_51_50_95divide = function (a, b) { return (a / b) | 0; };
var i_51_50_95multiply = function (a, b) { return (a * b) | 0; };
var i_51_50_95negate = function (a) { return -a | 0; };
var nil = [];
var cons = function (first, rest) { return [first, rest]; };
var first = function (list) { return list === nil ? nil : list[0]; };
var rest = function (list) { return list === nil ? nil : list[1]; };
var is_95nil = function (list) { return list === nil ? true : false; };
