name: Performance

on:
  push:
    branches: [base]
  pull_request:
    branches: [base]

jobs:
  measure:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up dependencies (Ubuntu)
        run: sudo apt-get install ocaml-nox ghc

      - name: Run performance test
        run: $GITHUB_WORKSPACE/measure/performance.sh

      - uses: actions/upload-artifact@v2
        with:
          name: report
          path: $GITHUB_WORKSPACE/generated/measure/report.csv
